solver_options:
    regularization: 1e-12
    back_end: qpoases
    front_end: ihqp

stack:
     - [LF, RF, LR, RR, IMU]

constraints: [Postural]

Postural:
    type: Postural
    lambda: 0.
    disabled_joints:
        - VIRTUALJOINT_1
        - VIRTUALJOINT_2
        - VIRTUALJOINT_3
        - VIRTUALJOINT_4
        - VIRTUALJOINT_5
        - VIRTUALJOINT_6

IMU:
    type: Cartesian
    distal_link: imu_link
    lambda: 0.1
    indices: [3,4,5]
    weight: 1.
    active: false

LF:
    type: Cartesian
    distal_link: contact_1
    indices: [0, 1, 2]

RF:
    type: Cartesian
    distal_link: contact_2
    indices: [0, 1, 2]

LR:
    type: Cartesian
    distal_link: contact_3
    indices: [0, 1, 2]

RR:
    type: Cartesian
    distal_link: contact_4
    indices: [0, 1, 2]
