control_mode:
    J_wheel_A: 26
    J_wheel_B: 26
    J_wheel_C: 26
    J_wheel_D: 26

define:
#    - &low_stiff 0.
#    - &low_damp 0.
    - &low_stiff 50.
    - &low_damp 5.
    - &high_stiff 2000.
    - &high_damp 100.

stiffness:
    'J1_A': *low_stiff
    'J1_B': *low_stiff
    'J1_C': *low_stiff
    'J1_D': *low_stiff
    'J1_E': *low_stiff
    'J2_E': *low_stiff
    'J3_E': *low_stiff
    'J4_E': *low_stiff
    'J5_E': *low_stiff
    'J6_E': *low_stiff
    J_wheel_A: 0
    J_wheel_B: 0
    J_wheel_C: 0
    J_wheel_D: 0

damping:
    'J1_A': *low_damp
    'J1_B': *low_damp
    'J1_C': *low_damp
    'J1_D': *low_damp
    'J1_E': *low_damp
    'J2_E': *low_damp
    'J3_E': *low_damp
    'J4_E': *low_damp
    'J5_E': *low_damp
    'J6_E': *low_damp
    J_wheel_A: 0
    J_wheel_B: 0
    J_wheel_C: 0
    J_wheel_D: 0

