horizon_duration: 1.5
n_nodes: 30

define:
#    - &stiff 50.
#    - &damp 2.
    - &stiff 1500.
    - &damp 100.

stiffness:

   hip_pitch_1: *stiff
   hip_pitch_2: *stiff
   hip_pitch_3: *stiff
   hip_pitch_4: *stiff
   hip_roll_1: *stiff
   hip_roll_2: *stiff
   hip_roll_3: *stiff
   hip_roll_4: *stiff
   knee_pitch_1: *stiff
   knee_pitch_2: *stiff
   knee_pitch_3: *stiff
   knee_pitch_4: *stiff

damping:
   hip_pitch_1: *damp
   hip_pitch_2: *damp
   hip_pitch_3: *damp
   hip_pitch_4: *damp
   hip_roll_1: *damp
   hip_roll_2: *damp
   hip_roll_3: *damp
   hip_roll_4: *damp
   knee_pitch_1: *damp
   knee_pitch_2: *damp
   knee_pitch_3: *damp
   knee_pitch_4: *damp


